### ISSUE TITLE
Return invalid fields on validation error

### ISSUE THREAD

**Issue by bchatelard** [online-labs/postal-address#7]
When validating an address using `address.validate()`, on error the method always raises a `ValueError`.
We can also use the `address.valid()` method, but we do not have the information about what field is invalid.

It would be great if you could expose a new property like `address.errors` that returns a dict with something like `{'field': 'error'}`.

And maybe also embed in the exception body this dict.

**Comment by kdeldycke** [comment]
:+1: Feel free to send a PR ! :)
